source 'https://rubygems.org'

gem 'rake'
gem 'afmotion'
gem 'motion-cocoapods'
gem 'bubble-wrap'
gem 'motion-i18n'
gem 'motion-fontawesome', :git => 'git@github.com:trivektor/fontawesome.git'
gem 'sugarcube', :require => 'sugarcube-all'
gem 'formotion'
gem 'teacup'